"""Initial migration

Revision ID: 683be43da148
Revises:
Create Date: 2025-12-03 14:52:30.262935

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "683be43da148"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)

    op.create_table(
        "stop_searches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("force", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("involved_person", sa.Boolean(), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operation", sa.Boolean(), nullable=True),
        sa.Column("operation_name", sa.String(), nullable=True),
        sa.Column("latitude", sa.String(), nullable=True),
        sa.Column("longitude", sa.String(), nullable=True),
        sa.Column("street_id", sa.Integer(), nullable=True),
        sa.Column("street_name", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("age_range", sa.String(), nullable=True),
        sa.Column("self_defined_ethnicity", sa.String(), nullable=True),
        sa.Column("officer_defined_ethnicity", sa.String(), nullable=True),
        sa.Column("legislation", sa.String(), nullable=True),
        sa.Column("object_of_search", sa.String(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("outcome_linked_to_object_of_search", sa.Boolean(), nullable=True),
        sa.Column("removal_of_more_than_outer_clothing", sa.Boolean(), nullable=True),
        sa.Column("outcome_object_id", sa.String(), nullable=True),
        sa.Column("outcome_object_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_stop_searches_datetime"), "stop_searches", ["datetime"], unique=False
    )
    op.create_index(
        op.f("ix_stop_searches_force"), "stop_searches", ["force"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stop_searches_id"), table_name="stop_searches")
    op.drop_index(op.f("ix_stop_searches_force"), table_name="stop_searches")
    op.drop_index(op.f("ix_stop_searches_datetime"), table_name="stop_searches")
    op.drop_table("stop_searches")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_failed_rows_id"), table_name="failed_rows")
    op.drop_table("failed_rows")
    # ### end Alembic commands ###
